name: Tests + Publish

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: oven/bun:latest
    steps:
      - uses: actions/checkout@v4
      - run: bun install
      - run: bun test

  publish:
    runs-on: ubuntu-latest
    needs: test
    container:
      image: oven/bun:latest
    steps:
      - uses: actions/checkout@v4
      - run: bun install
      - run: bun run build
      - run: bunx --bun npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}